runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
# Use a simpler, but more explicit handler structure for static files
- url: /static
  static_dir: static
  secure: always
  expiration: "7d"
  http_headers:
    Cache-Control: "public, max-age=604800"

# Add specific handler for dist CSS
- url: /static/dist/css
  static_dir: static/dist/css
  mime_type: text/css
  secure: always
  expiration: "365d"
  http_headers:
    Cache-Control: "public, max-age=31536000"
    Content-Type: "text/css; charset=utf-8"

# Add specific handler for dist JS
- url: /static/dist/js
  static_dir: static/dist/js
  mime_type: application/javascript
  secure: always
  expiration: "365d" 
  http_headers:
    Cache-Control: "public, max-age=31536000"
    Content-Type: "application/javascript; charset=utf-8"

# Add specific handler for dist images
- url: /static/dist/images
  static_dir: static/dist/images
  secure: always
  expiration: "365d"
  http_headers:
    Cache-Control: "public, max-age=31536000"

- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_APP: app.py
  FLASK_CONFIG: production
  PYTHONUNBUFFERED: "true"
  LOG_LEVEL: "INFO"

instance_class: F2

automatic_scaling:
  max_instances: 20