runtime: python312
entrypoint: gunicorn -b :$PORT app:app
handlers:
- url: /static
  static_dir: static
  secure: always
  expiration: 7d
  http_headers:
    Cache-Control: public, max-age=604800
- url: /
  script: auto
  secure: optional
- url: /.*
  script: auto
  secure: always
env_variables:
  FLASK_APP: app.py
  FLASK_CONFIG: production
  PYTHONUNBUFFERED: 'true'
  LOG_LEVEL: INFO
instance_class: F2
automatic_scaling:
  min_idle_instances: 1
  max_instances: 20
