runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
  # Serve all static files (including dist) under /static/
- url: /static/(.*)
  static_dir: static
  secure: always
  expiration: "7d"
  http_headers:
    Cache-Control: "public, max-age=604800"


- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_APP: app.py
  FLASK_CONFIG: production
  PYTHONUNBUFFERED: "true"
  LOG_LEVEL: "INFO"

instance_class: F2

automatic_scaling:
  max_instances: 20