runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /static/dist/(.*)
  static_files: static/dist/\1
  upload: static/dist/(.*)
  secure: always
  expiration: "365d"

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always
  expiration: "7d"

- url: /.*
  script: auto
  secure: always

env_variables:
  FLASK_APP: app.py
  FLASK_CONFIG: production
  PYTHONUNBUFFERED: "true"
  LOG_LEVEL: "INFO"

instance_class: F2

automatic_scaling:
  max_instances: 20