name: Deploy to Google App Engine

on:
  # Trigger deployment only when pushing to the master branch
  push:
    branches: [ master ]
  
  # Allow manual deployment
  workflow_dispatch:

jobs:
  test-and-deploy:
    name: Test and Deploy to Google App Engine
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        # Install mock TensorFlow for CI environment
        pip install tensorflow-cpu>=2.12.0
        # Install the package with dev dependencies
        pip install -e ".[dev]"
    
    - name: Create Mock ML Model
      run: |
        mkdir -p data
        # Create a dummy model file for testing
        pip install h5py
        python -c "import h5py; f = h5py.File('data/model.h5', 'w'); f.close()"
    
    - name: Run backend tests
      run: |
        pytest
    
    - name: Set up Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: frontend/package.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test
    
    - name: Install Elm
      run: npm install -g elm
    
    - name: Build frontend assets
      run: |
        cd frontend
        npm run build
        cp -r dist ../static/
    
    - name: Build Elm assets
      run: |
        elm make elm/Home.elm --output=static/js/home.js --optimize
        elm make elm/Asteroids.elm --output=static/js/asteroids.js --optimize
    
    - name: Install production dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Authenticate with Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Deploy to App Engine
      id: deploy
      uses: google-github-actions/deploy-appengine@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        deliverables: app.yaml
    
    - name: Print deployment URL
      run: echo "Deployed to ${{ steps.deploy.outputs.url }}"